# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 11:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='modify',
        ),
        migrations.AddField(
            model_name='list',
            name='date',
            field=models.DateField(default=datetime.date(2017, 2, 10), verbose_name='date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='listType',
            field=models.CharField(choices=[('I', 'Income'), ('E', 'Expenses')], default='I', max_length=1),
            preserve_default=False,
        ),
    ]
