# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_start_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('actionType', models.CharField(choices=[('I', 'Income'), ('E', 'Expenses')], max_length=1)),
                ('description', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
        migrations.RemoveField(
            model_name='list',
            name='account',
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
